# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
# avoid duplicate tests in PRs
branches:
  only:
    - master
os:
  - linux
#  - osx
julia:
  - 1.4
addons:
  apt:
    packages:
      # later on for checking it against openssl
      # - openssl
notifications:
  email: false
